version: '3.7'

networks:
  homeinfra_default:
    external: true

volumes:
    prometheus_data:
      external: true
    grafana_data:
      external: true

services:

  prometheus:
    image: prom/prometheus:v2.18.1
    user: "1002:994"
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - homeinfra_default
    labels:
      - "org.label-schema.group: monitoring"
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMURL}`)"

      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

      - "traefik.http.routers.prometheus-secure.entrypoints=websecure"
      - "traefik.http.routers.prometheus-secure.rule=Host(`${PROMURL}`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"

  # alertmanager:
  #   image: prom/alertmanager:v0.20.0
  #   container_name: alertmanager
  #   volumes:
  #     - ./alertmanager:/etc/alertmanager
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #   restart: unless-stopped
  #   expose:
  #     - 9093
  #   networks:
  #     - homeinfra_default
  #   labels:
  #     org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - homeinfra_default
    labels:
      - "org.label-schema.group: monitoring"
      
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    privileged: true
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - homeinfra_default
    labels:
      - "org.label-schema.group: monitoring"
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.entrypoints=web"
      - "traefik.http.routers.cadvisor.rule=Host(`${CADVISORURL}`)"

      - "traefik.http.routers.cadvisor.middlewares=cadvisor-https-redirect"
      - "traefik.http.middlewares.cadvisor-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"

      - "traefik.http.routers.cadvisor-secure.entrypoints=websecure"
      - "traefik.http.routers.cadvisor-secure.rule=Host(`${CADVISORURL}`)"
      - "traefik.http.routers.cadvisor-secure.tls=true"
      - "traefik.http.routers.cadvisor-secure.service=cadvisor"

  grafana:
    image: grafana/grafana:6.7.3
    user: "1002:994"
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - homeinfra_default
    labels:
      - "org.label-schema.group: monitoring"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANAURL}`)"

      - "traefik.http.routers.grafana.middlewares=grafana-https-redirect"
      - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.rule=Host(`${GRAFANAURL}`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.service=grafana"

  # pushgateway:
  #   image: prom/pushgateway:v1.2.0
  #   container_name: pushgateway
  #   restart: unless-stopped
  #   expose:
  #     - 9091
  #   networks:
  #     - homeinfra_default
  #   labels:
  #     org.label-schema.group: "monitoring"

  # caddy:
  #   image: stefanprodan/caddy
  #   container_name: caddy
  #   ports:
  #     - "3000:3000"
  #     - "9090:9090"
  #     - "9093:9093"
  #     - "9091:9091"
  #   volumes:
  #     - ./caddy:/etc/caddy
  #   environment:
  #     - ADMIN_USER=${ADMIN_USER:-admin}
  #     - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
  #   restart: unless-stopped
  #   networks:
  #     - monitor-net
  #   labels:
  #     org.label-schema.group: "monitoring"
